#!/usr/bin/env python3
"""Export campaign data from markdown files to a single JSON file.

This script runs locally (not on the server). It parses campaign markdown
files and outputs a JSON file ready for upload to the app via
POST /api/contacts/import-json.

Usage:
    # Export a campaign:
    python3 importer/export_json.py --campaign example_campaign -o export.json

    # List available campaigns:
    python3 importer/export_json.py --list
"""

import argparse
import json
import os
import sys

# Ensure we can import from the app package
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from importer.markdown_parser import parse_generic_campaign

CAMPAIGNS_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), '..', '..', 'campaigns')
)

# Campaign metadata registry — loaded from campaigns_meta.json if it exists
# (auto-generated by the app when you save your profile), otherwise fallback.
_CAMPAIGNS_META_PATH = os.path.join(CAMPAIGNS_DIR, 'campaigns_meta.json')

def _load_campaign_meta():
    """Load campaign metadata from campaigns_meta.json or use defaults."""
    if os.path.exists(_CAMPAIGNS_META_PATH):
        with open(_CAMPAIGNS_META_PATH, 'r') as f:
            return json.load(f)
    return {
        'example_campaign': {
            'name': 'Example Outreach Campaign',
            'description': 'Example outreach campaign',
            'campaign_file': 'example_outreach_campaign.md',
            'parser': 'generic',
            'max_emails_per_day': 15,
        },
    }

CAMPAIGN_META = _load_campaign_meta()


def export_generic_campaign(campaign_key):
    """Export any non-DC campaign using the generic parser."""
    meta = CAMPAIGN_META[campaign_key]
    campaign_dir = os.path.join(CAMPAIGNS_DIR, campaign_key)
    campaign_file = os.path.join(campaign_dir, meta['campaign_file'])

    if not os.path.exists(campaign_file):
        raise FileNotFoundError(f"Campaign file not found: {campaign_file}")

    parsed = parse_generic_campaign(campaign_file)
    return _build_json(parsed, meta)


def _build_json(contacts, meta):
    """Build the standard JSON export structure from parsed contacts."""
    contacts_json = []
    for pc in contacts:
        if pc.get('is_dropped', False):
            continue

        contact = {
            'external_id': str(pc['external_id']),
            'name': pc.get('name', ''),
            'company': pc.get('company', ''),
            'title': pc.get('title', ''),
            'email': pc.get('email', ''),
            'email_confidence': pc.get('email_confidence', ''),
            'response_likelihood': pc.get('response_likelihood', 0),
            'wave': pc.get('wave', 0),
            'ask_type': pc.get('ask_type', ''),
            'status_raw': pc.get('status_raw', ''),
            'needs_linkedin': pc.get('needs_linkedin', False),
            'personalization_hooks': pc.get('personalization_hooks', ''),
            'emails': [],
        }

        email_types = [
            ('initial', pc.get('initial_subject', ''), pc.get('initial_body', '')),
            ('followup1', pc.get('followup1_subject', ''), pc.get('followup1_body', '')),
            ('followup2', pc.get('followup2_subject', ''), pc.get('followup2_body', '')),
        ]

        for email_type, subject, body in email_types:
            contact['emails'].append({
                'email_type': email_type,
                'subject': subject or '(no subject)',
                'body': body or '(no content - needs writing)',
            })

        contacts_json.append(contact)

    return {
        'campaign': {
            'name': meta['name'],
            'description': meta.get('description', ''),
            'send_start_hour': 8,
            'send_end_hour': 17,
            'max_emails_per_day': meta.get('max_emails_per_day', 15),
            'min_interval_minutes': 15,
            'followup1_delay_days': 3,
            'followup2_delay_days': 7,
            'timezone': 'America/Los_Angeles',
        },
        'contacts': contacts_json,
    }


def list_campaigns():
    """Print available campaigns and their status."""
    print("Available campaigns:\n")
    for key, meta in CAMPAIGN_META.items():
        campaign_dir = os.path.join(CAMPAIGNS_DIR, key)
        campaign_file = os.path.join(campaign_dir, meta['campaign_file'])
        exists = os.path.exists(campaign_file)
        status = "READY" if exists else "MISSING"
        print(f"  {key:30s} [{status}] {meta['name']}")
        if exists:
            print(f"    File: {campaign_file}")
    print()


def main():
    parser = argparse.ArgumentParser(
        description='Export campaign markdown to JSON for app import'
    )
    parser.add_argument('--output', '-o', help='Output file path (default: stdout)')
    parser.add_argument(
        '--campaign', '-c',
        help='Campaign folder name (e.g., example_campaign). '
             'Default: example_campaign',
        default='example_campaign',
    )
    parser.add_argument(
        '--list', action='store_true',
        help='List available campaigns and exit',
    )
    args = parser.parse_args()

    if args.list:
        list_campaigns()
        return

    campaign_key = args.campaign
    if campaign_key not in CAMPAIGN_META:
        print(f"Error: Unknown campaign '{campaign_key}'", file=sys.stderr)
        print(f"Available: {', '.join(CAMPAIGN_META.keys())}", file=sys.stderr)
        sys.exit(1)

    meta = CAMPAIGN_META[campaign_key]

    data = export_generic_campaign(campaign_key)

    output = json.dumps(data, indent=2, ensure_ascii=False)

    if args.output:
        with open(args.output, 'w', encoding='utf-8') as f:
            f.write(output)
        print(
            f"Exported {len(data['contacts'])} contacts from "
            f"'{meta['name']}' to {args.output}",
            file=sys.stderr,
        )
    else:
        print(output)
        print(
            f"\nExported {len(data['contacts'])} contacts from '{meta['name']}'",
            file=sys.stderr,
        )


if __name__ == '__main__':
    main()
